[mypy]
ignore_missing_imports = True
check_untyped_defs = False
warn_no_return = False
warn_unused_ignores = False
disallow_untyped_defs = False

[mypy-interfaces.telegram_bot]
disable_error_code = union-attr  # Abaikan Message | None error
